apiVersion: v1
kind: Service
metadata:
  name: device-service
  namespace: telecom-platform
  labels:
    app.kubernetes.io/name: device-service
    app.kubernetes.io/part-of: telecom-platform
spec:
  type: ClusterIP
  selector:
    app: device-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
