apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: telecom-platform

type: Opaque

stringData:
  POSTGRES_USER: platform_admin
  POSTGRES_PASSWORD: ChangeMe123!
  POSTGRES_DB: platform_db
