apiVersion: v1
kind: ConfigMap

metadata:
  name: platform-config
  namespace: telecom-platform

data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
