apiVersion: v1
kind: Secret

metadata:
  name: platform-secret
  namespace: telecom-platform

type: Opaque

stringData:
  POSTGRES_USER: platform_admin
  POSTGRES_PASSWORD: ChangeMe123!
  POSTGRES_DB: platform_db

  RABBITMQ_USER: admin
  RABBITMQ_PASSWORD: ChangeMe123!

